# NumPy

In [2]:
import numpy as np

In [4]:
arr = np.array([[5,3],
              [9,1,],
              [6,7]])

In [7]:
add = arr + 3.2

In [8]:
print(add)

[[ 8.2  6.2]
 [12.2  4.2]
 [ 9.2 10.2]]


In [13]:
arr2 =np.array([[3,4],[9,6],[7,3]])
result=np.ones_like(arr2)
print(result)

[[1 1]
 [1 1]
 [1 1]]


In [20]:
arr3 =np.array([[3,4],[1,7]])
arr4 =np.array([[8,9],[2,6]])
np.dot(arr3,arr4)

array([[32, 51],
       [22, 51]])

In [26]:
arr5=np.array([[32, 51],[22, 51]])
arr5.shape
arr5[0:1]

array([[32, 51]])

In [29]:
np.sum([[32, 51]])

83